import { IntProduct, IntSubscription } from '@/utils/types';

export const products: IntSubscription[] = [
  {
    title: 'Governance structure',
    price: 399,
    priceApi: 'price_1PeOkIJrU3Or1CooWNiX5TOw',
    id: 1,
    type: 'startup',
    data: [
      'We manage on your behalf the governance structure in the company, including ongoing support to the employees that are responsible for data compliance',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Governance structure',
    price: 799,
    priceApi: 'price_1PeOkIJrU3Or1CooLk8zeTZr',
    id: 2,
    type: 'micro',
    data: [
      'We manage on your behalf the governance structure in the company, including ongoing support to the employees that are responsible for data compliance',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Governance structure',
    price: 1199,
    priceApi: 'price_1PeOkIJrU3Or1CoozjTMy0xA',
    id: 3,
    type: 'sme',
    data: [
      'We manage on your behalf the governance structure in the company, including ongoing support to the employees that are responsible for data compliance',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Personal data inventory and data transfer mechanisms',
    price: 499,
    priceApi: 'price_1PeOkOJrU3Or1CooeOiXCZTD',
    id: 4,
    type: 'startup',
    data: [
      'We manage on your behalf the RoPA (record of processing activities, GDPR Art.30), including data transfer mechanism',
      'We monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Personal data inventory and data transfer mechanisms',
    price: 999,
    priceApi: 'price_1PeOkOJrU3Or1Coo1QRZ50Iu',
    id: 5,
    type: 'micro',
    data: [
      'We manage on your behalf the RoPA (record of processing activities, GDPR Art.30), including data transfer mechanism',
      'We monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Personal data inventory and data transfer mechanisms',
    price: 1499,
    priceApi: 'price_1PeOkOJrU3Or1Cooo7zq9rlc',
    id: 6,
    type: 'sme',
    data: [
      'We manage on your behalf the RoPA (record of processing activities, GDPR Art.30), including data transfer mechanism',
      'We monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Embed data compliance into current and new operations',
    price: 599,
    priceApi: 'price_1PeOkUJrU3Or1CooCHQuMRS9',
    id: 7,
    type: 'startup',
    data: [
      'We manage on your behalf the necessary internal policies, processes and procedures (e.g. employee privacy policy, before-during-after employment, CCTV etc.)',
      'Manage privacy and security by design into new operations (e.g. ensure that new projects and processing activities follow data compliance principles)',
      'Conduct periodic testing and report the effectiveness',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Embed data compliance into current and new operations',
    price: 1199,
    priceApi: 'price_1PeOkTJrU3Or1Coo4LB3U74J',
    id: 8,
    type: 'micro',
    data: [
      'We manage on your behalf the necessary internal policies, processes and procedures (e.g. employee privacy policy, before-during-after employment, CCTV etc.)',
      'Manage privacy and security by design into new operations (e.g. ensure that new projects and processing activities follow data compliance principles)',
      'Conduct periodic testing and report the effectiveness',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Embed data compliance into current and new operations',
    price: 1799,
    priceApi: 'price_1PeOkTJrU3Or1CooEB6CGdul',
    id: 9,
    type: 'sme',
    data: [
      'We manage on your behalf the necessary internal policies, processes and procedures (e.g. employee privacy policy, before-during-after employment, CCTV etc.)',
      'Manage privacy and security by design into new operations (e.g. ensure that new projects and processing activities follow data compliance principles)',
      'Conduct periodic testing and report the effectiveness',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'External policies and notices to individuals',
    price: 599,
    priceApi: 'price_1PeOkWJrU3Or1Coo7KGXrxOG',
    id: 76,
    type: 'startup',
    data: [
      'We manage on your behalf the necessary external policies and notices to individuals consistent with data compliance regulations and operational risk tolerance, including the direct marketing and electronic communications areas (e.g. website, newsletter, social media campaigns etc.)',
      'Monitor and implement new compliance requirements and best practices',
      'Conduct periodic testing and report the effectiveness',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'External policies and notices to individuals',
    price: 1199,
    priceApi: 'price_1PeOkWJrU3Or1Cooa5oSmFPP',
    id: 77,
    type: 'micro',
    data: [
      'We manage on your behalf the necessary external policies and notices to individuals consistent with data compliance regulations and operational risk tolerance, including the direct marketing and electronic communications areas (e.g. website, newsletter, social media campaigns etc.)',
      'Monitor and implement new compliance requirements and best practices',
      'Conduct periodic testing and report the effectiveness',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'External policies and notices to individuals',
    price: 1799,
    priceApi: 'price_1PeOkWJrU3Or1CooEuzbQKvN',
    id: 78,
    type: 'sme',
    data: [
      'We manage on your behalf the necessary external policies and notices to individuals consistent with data compliance regulations and operational risk tolerance, including the direct marketing and electronic communications areas (e.g. website, newsletter, social media campaigns etc.)',
      'Monitor and implement new compliance requirements and best practices',
      'Conduct periodic testing and report the effectiveness',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },

  {
    title:
      'Conduct the necessary ongoing risk assessments for current and new operations',
    price: 1599,
    priceApi: 'price_1PeOlYJrU3Or1CooEHwmaxvm',
    id: 28,
    type: 'startup',
    data: [
      'We conduct the necessary ongoing risk assessments for current and new operations',
    ],
    option: 'subscription',
  },
  {
    title:
      'Conduct the necessary ongoing risk assessments for current and new operations',
    price: 1599,
    priceApi: 'price_1PeOlYJrU3Or1CooEHwmaxvm',
    id: 29,
    type: 'micro',
    data: [
      'We conduct the necessary ongoing risk assessments for current and new operations',
    ],
    option: 'subscription',
  },
  {
    title:
      'Conduct the necessary ongoing risk assessments for current and new operations',
    price: 1599,
    priceApi: 'price_1PeOlYJrU3Or1CooEHwmaxvm',
    id: 30,
    type: 'sme',
    data: [
      'We conduct the necessary ongoing risk assessments for current and new operations',
    ],
    option: 'subscription',
  },

  {
    title: 'Basic information security',
    price: 799,
    priceApi: 'price_1PeOkYJrU3Or1Cooe6MgNu5e',
    id: 10,
    type: 'startup',
    data: [
      'Maintain a basic information security program based on legal requirements, international standards and ongoing risk assessments and risk tolerance (e.g. security policy, security measures, contingency plan etc.)',
      'Conduct periodic testing of the information security program and report the effectiveness of the program',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Basic information security',
    price: 1599,
    priceApi: 'price_1PeOkYJrU3Or1Cool9T9VO6w',
    id: 11,
    type: 'micro',
    data: [
      'Maintain a basic information security program based on legal requirements, international standards and ongoing risk assessments and risk tolerance (e.g. security policy, security measures, contingency plan etc.)',
      'Conduct periodic testing of the information security program and report the effectiveness of the program',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Basic information security',
    price: 2399,
    priceApi: 'price_1PeOkYJrU3Or1CoosKv5KL3c',
    id: 12,
    type: 'sme',
    data: [
      'Maintain a basic information security program based on legal requirements, international standards and ongoing risk assessments and risk tolerance (e.g. security policy, security measures, contingency plan etc.)',
      'Conduct periodic testing of the information security program and report the effectiveness of the program',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Respond to requests and complaints from individuals',
    price: 449,
    priceApi: 'price_1PeOlKJrU3Or1Coo4fGuPRI5',
    id: 13,
    type: 'startup',
    data: [
      'Respond to individuals requests (e.g. deletion, access)',
      'Respond to individuals complaints',
      'Conduct periodic testing of the processes and procedures to address requests and complaints from individuals, and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Respond to requests and complaints from individuals',
    price: 749,
    priceApi: 'price_1PeOlKJrU3Or1CoopIlWb1sP',
    id: 14,
    type: 'micro',
    data: [
      'Respond to individuals requests (e.g. deletion, access)',
      'Respond to individuals complaints',
      'Conduct periodic testing of the processes and procedures to address requests and complaints from individuals, and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Respond to requests and complaints from individuals',
    price: 1249,
    priceApi: 'price_1PeOlKJrU3Or1CoosTELpQs3',
    id: 15,
    type: 'sme',
    data: [
      'Respond to individuals requests (e.g. deletion, access)',
      'Respond to individuals complaints',
      'Conduct periodic testing of the processes and procedures to address requests and complaints from individuals, and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Vendor management',
    price: 2499,
    priceApi: 'price_1PeOlMJrU3Or1CooMcg2EUe2',
    id: 16,
    type: 'startup',
    data: [
      'Manage the record of all data processors, sub-processors and joint controllers',
      'Manage the data processors due diligence before onboarding a new vendor, including assessment and security questionnaire',
      'Manage data processing agreements drafting and negotiations',
      'Manage data processors audit',
      'Conduct periodic testing of the vendor management process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Vendor management',
    price: 3998,
    priceApi: 'price_1PeOlMJrU3Or1CooXj8cIYac',
    id: 17,
    type: 'micro',
    data: [
      'Manage the record of all data processors, sub-processors and joint controllers',
      'Manage the data processors due diligence before onboarding a new vendor, including assessment and security questionnaire',
      'Manage data processing agreements drafting and negotiations',
      'Manage data processors audit',
      'Conduct periodic testing of the vendor management process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Vendor management',
    price: 5499,
    priceApi: 'price_1PeOlMJrU3Or1CooiwEqETne',
    id: 18,
    type: 'sme',
    data: [
      'Manage the record of all data processors, sub-processors and joint controllers',
      'Manage the data processors due diligence before onboarding a new vendor, including assessment and security questionnaire',
      'Manage data processing agreements drafting and negotiations',
      'Manage data processors audit',
      'Conduct periodic testing of the vendor management process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Incident management',
    price: 749,
    priceApi: 'price_1PeOlRJrU3Or1CoodIHK4ySP',
    id: 19,
    type: 'startup',
    data: [
      'Management of personal data breach cases including notification to the Data Protection Agency and communication to individuals, if necessary',
      'Keep the personal data breach record updated ',
      'Conduct periodic testing of the data breach process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Incident management',
    price: 949,
    priceApi: 'price_1PeOlRJrU3Or1CooQuHEzSUV',
    id: 20,
    type: 'micro',
    data: [
      'Management of personal data breach cases including notification to the Data Protection Agency and communication to individuals, if necessary',
      'Keep the personal data breach record updated ',
      'Conduct periodic testing of the data breach process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Incident management',
    price: 1499,
    priceApi: 'price_1PeOlRJrU3Or1Coo1BKp5wbg',
    id: 21,
    type: 'sme',
    data: [
      'Management of personal data breach cases including notification to the Data Protection Agency and communication to individuals, if necessary',
      'Keep the personal data breach record updated ',
      'Conduct periodic testing of the data breach process and report the effectiveness of the process',
      'Monitor and implement new compliance requirements and best practices',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Training and awareness program',
    price: 549,
    priceApi: 'price_1PeOlTJrU3Or1CoooxYGyr4w',
    id: 22,
    type: 'startup',
    data: [
      'Providing ongoing online training for employees to promote data compliance and to mitigate operational risks',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Training and awareness program',
    price: 849,
    priceApi: 'price_1PeOlTJrU3Or1CooJnLX5wYo',
    id: 23,
    type: 'micro',
    data: [
      'Providing ongoing online training for employees to promote data compliance and to mitigate operational risks',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title: 'Training and awareness program',
    price: 1499,
    priceApi: 'price_1PeOlTJrU3Or1Coo8N5QKfm3',
    id: 24,
    type: 'sme',
    data: [
      'Providing ongoing online training for employees to promote data compliance and to mitigate operational risks',
      'We perform an assessment toghether with you in order to find the high risk compliance areas that needs your full attention',
      'We schedule an online onboarding to get things started',
      'We are available 24/7 and reach out to you as soon as possilble. We assess your needs and reach out faster for a data breach case than for a more general question',
      'We believe that is very important for you to stay informed on the compliance efforts. We always assess the current situation and do not wait 3 months to inform you on issues that needs your attention',
    ],
    option: 'subscription',
  },
  {
    title:
      'Point of contact for local Data Protection Agency and assisting in a potential audit from local Data Protection Agency',
    price: 399,
    priceApi: 'price_1PeOlWJrU3Or1CooiUk21NRB',
    id: 25,
    type: 'startup',
    data: [
      'We are the point of contact for your local Data Protection Agency and we assist you in a potential audit from your local Data Protection Agency',
    ],
    option: 'subscription',
  },
  {
    title:
      'Point of contact for local Data Protection Agency and assisting in a potential audit from local Data Protection Agency',
    price: 399,
    priceApi: 'price_1PeOlWJrU3Or1CooiUk21NRB',
    id: 26,
    type: 'micro',
    data: [
      'We are the point of contact for your local Data Protection Agency and we assist you in a potential audit from your local Data Protection Agency',
    ],
    option: 'subscription',
  },
  {
    title:
      'Point of contact for local Data Protection Agency and assisting in a potential audit from local Data Protection Agency',
    price: 399,
    priceApi: 'price_1PeOlWJrU3Or1CooiUk21NRB',
    id: 27,
    type: 'sme',
    data: [
      'We are the point of contact for your local Data Protection Agency and we assist you in a potential audit from your local Data Protection Agency',
    ],
    option: 'subscription',
  },
];

export const subscriptions: IntSubscription[] = [
 
  
  {
    title: 'GDPR Light implementation',
    price: 1500,
    priceApi: 'price_1PeOlaJrU3Or1CooA1cx14l9',
    id: 34,
    type: 'startup',
    data: [
      'We provide a light implementation and is used by our clients that already have done some implementation. The price per month is only for a 12 month period',
    ],
    option: 'addon',
  },
  {
    title: 'GDPR Light implementation',
    price: 2500,
    priceApi: 'price_1PeOlaJrU3Or1CoomsM605hG',
    id: 35,
    type: 'micro',
    data: [
      'We provide a light implementation and is used by our clients that already have done some implementation. The price per month is only for a 12 month period',
    ],
    option: 'addon',
  },
  {
    title: 'GDPR Light implementation',
    price: 3500,
    priceApi: 'price_1PeOlaJrU3Or1CooCxa5kXjm',
    id: 36,
    type: 'sme',
    data: [
      'We provide a light implementation and is used by our clients that already have done some implementation. The price per month is only for a 12 month period',
    ],
    option: 'addon',
  },
  {
    title: 'GDPR Total implementation',
    price: 2500,
    priceApi: 'price_1PeOlcJrU3Or1CooarILxscH',
    id: 37,
    type: 'startup',
    data: [
      'We provide a total implementation and is used by our clients that need to implement everything. The prices per month is only for a 12 month period',
    ],
    option: 'addon',
  },
  {
    title: 'GDPR Total implementation',
    price: 3500,
    priceApi: 'price_1PeOlcJrU3Or1CoohgDMQxl7',
    id: 38,
    type: 'micro',
    data: [
      'We provide a total implementation and is used by our clients that need to implement everything. The prices per month is only for a 12 month period',
    ],
    option: 'addon',
  },
  {
    title: 'GDPR Total implementation',
    price: 4500,
    priceApi: 'price_1PeOlcJrU3Or1CooQ43f1il3',
    id: 39,
    type: 'sme',
    data: [
      'We provide a total implementation and is used by our clients that need to implement everything. The prices per month is only for a 12 month period',
    ],
    option: 'addon',
  },

  {
    title:
      'Create and implement process and procedure for individuals rights and complaints',
    price: 4995,
    priceApi: 'price_1PeOlzJrU3Or1CooOYHZXd6M',
    id: 58,
    type: 'startup',
    data: [
      'Creating and implementing this process is crucial in your data compliance success',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement process and procedure for individuals rights and complaints',
    price: 9995,
    priceApi: 'price_1PeOlzJrU3Or1Coo2MoZeXHL',
    id: 59,
    type: 'micro',
    data: [
      'Creating and implementing this process is crucial in your data compliance success',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement process and procedure for individuals rights and complaints',
    price: 14995,
    priceApi: 'price_1PeOlzJrU3Or1CootslAyt3Z',
    id: 60,
    type: 'sme',
    data: [
      'Creating and implementing this process is crucial in your data compliance success',
    ],
    option: 'addon',
  },

  {
    title: 'Create and implement vendor management process',
    price: 4995,
    priceApi: 'price_1PeOm0JrU3Or1CookZGlzbBd',
    id: 61,
    type: 'startup',
    data: [
      'Creating and implementing a vendor management process is key in your data compliance success',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement vendor management process',
    price: 9995,
    priceApi: 'price_1PeOm0JrU3Or1CootdzDlNVt',
    id: 62,
    type: 'micro',
    data: [
      'Creating and implementing a vendor management process is key in your data compliance success',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement vendor management process',
    price: 14995,
    priceApi: 'price_1PeOm0JrU3Or1CooHyfdynMK',
    id: 63,
    type: 'sme',
    data: [
      'Creating and implementing a vendor management process is key in your data compliance success',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement a basic information security program',
    price: 9995,
    priceApi: 'price_1PeOm2JrU3Or1CooguuLoeNd',
    id: 64,
    type: 'startup',
    data: [
      'It is crucial to have at least basic information security implemented in your organisation',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement a basic information security program',
    price: 19995,
    priceApi: 'price_1PeOm2JrU3Or1Coo6roxvXU3',
    id: 65,
    type: 'micro',
    data: [
      'It is crucial to have at least basic information security implemented in your organisation',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement a basic information security program',
    price: 29995,
    priceApi: 'price_1PeOm2JrU3Or1CoooBT0Nzek',
    id: 66,
    type: 'sme',
    data: [
      'It is crucial to have at least basic information security implemented in your organisation',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement ROPA (record of processing activities, GDPR Art.30)',
    price: 4995,
    priceApi: 'price_1PeOm4JrU3Or1CoolfmsN5Vm',
    id: 67,
    type: 'startup',
    data: [
      'Creating and implementing RoPA takes a lot of work and expertise to do it once and do it right',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement ROPA (record of processing activities, GDPR Art.30)',
    price: 14995,
    priceApi: 'price_1PeOm4JrU3Or1CooHz8KDnV4',
    id: 68,
    type: 'micro',
    data: [
      'Creating and implementing RoPA takes a lot of work and expertise to do it once and do it right',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement ROPA (record of processing activities, GDPR Art.30)',
    price: 24995,
    priceApi: 'price_1PeOm4JrU3Or1CooWSFHznax',
    id: 69,
    type: 'sme',
    data: [
      'Creating and implementing RoPA takes a lot of work and expertise to do it once and do it right',
    ],
    option: 'addon',
  },

  {
    title:
      'Create and implement governance structure including basic data compliance training to the data compliance responsibles',
    price: 4995,
    priceApi: 'price_1PeOm6JrU3Or1Coo6kjgmKlB',
    id: 70,
    type: 'startup',
    data: [
      'Without a proper governance structure in your organization no data compliance initiative will stick',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement governance structure including basic data compliance training to the data compliance responsibles',
    price: 14995,
    priceApi: 'price_1PeOm6JrU3Or1CooeYPwzgjp',
    id: 71,
    type: 'micro',
    data: [
      'Without a proper governance structure in your organization no data compliance initiative will stick',
    ],
    option: 'addon',
  },
  {
    title:
      'Create and implement governance structure including basic data compliance training to the data compliance responsibles',
    price: 24995,
    priceApi: 'price_1PeOm6JrU3Or1CooUBfbg4W1',
    id: 72,
    type: 'sme',
    data: [
      'Without a proper governance structure in your organization no data compliance initiative will stick',
    ],
    option: 'addon',
  },

  {
    title: 'Create and implement incident management process',
    price: 9995,
    priceApi: 'price_1PeOm9JrU3Or1CoolDJCDeoU',
    id: 73,
    type: 'startup',
    data: [
      'When you have an incident you better have a data breach process that will guide what do to, how to assess your breach, who to get involved etc.',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement incident management process',
    price: 19995,
    priceApi: 'price_1PeOm9JrU3Or1Coo7JcBEjMB',
    id: 74,
    type: 'micro',
    data: [
      'When you have an incident you better have a data breach process that will guide what do to, how to assess your breach, who to get involved etc.',
    ],
    option: 'addon',
  },
  {
    title: 'Create and implement incident management process',
    price: 29995,
    priceApi: 'price_1PeOm9JrU3Or1CoomBh3CZcX',
    id: 75,
    type: 'sme',
    data: [
      'When you have an incident you better have a data breach process that will guide what do to, how to assess your breach, who to get involved etc.',
    ],
    option: 'addon',
  },
];

export const onetimeproduct: IntProduct[] = [
  // {
  //   title: 'Extra hours with our experts 10 hours (950 DKK / hour)',
  //   price: 9500,
  //   priceApi: 'price_1PeOlfJrU3Or1CooUrjKUwJX',
  //   id: 40,
  //   type: 'startup',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 10 hours (950 DKK / hour)',
  //   price: 9500,
  //   priceApi: 'price_1PeOlfJrU3Or1CooUrjKUwJX',
  //   id: 41,
  //   type: 'micro',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 10 hours (950 DKK / hour)',
  //   price: 9500,
  //   priceApi: 'price_1PeOlfJrU3Or1CooUrjKUwJX',
  //   id: 42,
  //   type: 'sme',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 20 hours (750 DKK / hour)',
  //   price: 15000,
  //   priceApi: 'price_1PeOlhJrU3Or1CoolkdaqsCZ',
  //   id: 43,
  //   type: 'startup',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 20 hours (750 DKK / hour)',
  //   price: 15000,
  //   priceApi: 'price_1PeOlhJrU3Or1CoolkdaqsCZ',
  //   id: 44,
  //   type: 'micro',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 20 hours (750 DKK / hour)',
  //   price: 15000,
  //   priceApi: 'price_1PeOlhJrU3Or1CoolkdaqsCZ',
  //   id: 45,
  //   type: 'sme',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 30 hours (650 DKK / hour)',
  //   price: 19500,
  //   priceApi: 'price_1PeOlkJrU3Or1CooLjE17FtE',
  //   id: 46,
  //   type: 'startup',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 30 hours (650 DKK / hour)',
  //   price: 19500,
  //   priceApi: 'price_1PeOlkJrU3Or1CooLjE17FtE',
  //   id: 47,
  //   type: 'micro',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Extra hours with our experts 30 hours (650 DKK / hour)',
  //   price: 19500,
  //   priceApi: 'price_1PeOlkJrU3Or1CooLjE17FtE',
  //   id: 48,
  //   type: 'sme',
  //   data: [
  //     'Some of our clients use this service for a specific project, interim services, training, review contracts or for a back-log situation. You decide the purpose. If you need more than 30 hours get in touch with us for a special discount',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Support line for in-house compliance team or DPO',
  //   price: 950,
  //   priceApi: 'price_1Pj2KUJrU3Or1CooKd5wNECz',
  //   id: 31,
  //   type: 'startup',
  //   data: [
  //     'This service provides support to your company in-house compliance team or in-house DPO, whether the support is advice or solving concrete tasks in all data compliance matters and in all sectors',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Support line for in-house compliance team or DPO',
  //   price: 950,
  //   priceApi: 'price_1Pj2KUJrU3Or1CooKd5wNECz',
  //   id: 32,
  //   type: 'micro',
  //   data: [
  //     'This service provides support to your company in-house compliance team or in-house DPO, whether the support is advice or solving concrete tasks in all data compliance matters and in all sectors',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Support line for in-house compliance team or DPO',
  //   price: 950,
  //   priceApi: 'price_1Pj2KUJrU3Or1CooKd5wNECz',
  //   id: 33,
  //   type: 'sme',
  //   data: [
  //     'This service provides support to your company in-house compliance team or in-house DPO, whether the support is advice or solving concrete tasks in all data compliance matters and in all sectors',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO as a Service',
  //   price: 950,
  //   priceApi: 'price_1Pj2M3JrU3Or1CoojZ45Rfa2',
  //   id: 79,
  //   type: 'startup',
  //   data: [
  //     'A highly experienced DPO will become instantly operational in your organization and act as part of it',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO as a Service',
  //   price: 950,
  //   priceApi: 'price_1Pj2M3JrU3Or1CoojZ45Rfa2',
  //   id: 80,
  //   type: 'micro',
  //   data: [
  //     'A highly experienced DPO will become instantly operational in your organization and act as part of it',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO as a Service',
  //   price: 950,
  //   priceApi: 'price_1Pj2M3JrU3Or1CoojZ45Rfa2',
  //   id: 81,
  //   type: 'sme',
  //   data: [
  //     'A highly experienced DPO will become instantly operational in your organization and act as part of it',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Interim DPO or data compliance consultant',
  //   price: 950,
  //   priceApi: 'price_1Pj2MaJrU3Or1CooGQhDd5br',
  //   id: 82,
  //   type: 'startup',
  //   data: [
  //     'This is a very flexible service available when you need it, whether is a maternity/paternity cover, between hire gaps, a one time project etc. If you need this service for more than one month get in touch for your special',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Interim DPO or data compliance consultant',
  //   price: 950,
  //   priceApi: 'price_1Pj2MaJrU3Or1CooGQhDd5br',
  //   id: 83,
  //   type: 'micro',
  //   data: [
  //     'This is a very flexible service available when you need it, whether is a maternity/paternity cover, between hire gaps, a one time project etc. If you need this service for more than one month get in touch for your special',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Interim DPO or data compliance consultant',
  //   price: 950,
  //   priceApi: 'price_1Pj2MaJrU3Or1CooGQhDd5br',
  //   id: 84,
  //   type: 'sme',
  //   data: [
  //     'This is a very flexible service available when you need it, whether is a maternity/paternity cover, between hire gaps, a one time project etc. If you need this service for more than one month get in touch for your special',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO online training',
  //   price: 14995,
  //   priceApi: 'price_1PeOlnJrU3Or1CooIesreAMW',
  //   id: 49,
  //   type: 'startup',
  //   data: [
  //     'Train with Nordic Data Compliance Centre if you are interested in a customized interactive one-on-one online training session',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO online training',
  //   price: 14995,
  //   priceApi: 'price_1PeOlnJrU3Or1CooIesreAMW',
  //   id: 50,
  //   type: 'micro',
  //   data: [
  //     'Train with Nordic Data Compliance Centre if you are interested in a customized interactive one-on-one online training session',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'DPO online training',
  //   price: 14995,
  //   priceApi: 'price_1PeOlnJrU3Or1CooIesreAMW',
  //   id: 51,
  //   type: 'sme',
  //   data: [
  //     'Train with Nordic Data Compliance Centre if you are interested in a customized interactive one-on-one online training session',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data compliance audit',
  //   price: 9995,
  //   priceApi: 'price_1PeOluJrU3Or1CooO7mrGyem',
  //   id: 52,
  //   type: 'startup',
  //   data: [
  //     'We perform a comprehensive, flexible and risk-based approach data compliance audit that will bring enormous value in your organization',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data compliance audit',
  //   price: 14995,
  //   priceApi: 'price_1PeOluJrU3Or1Coob7KwcCmX',
  //   id: 53,
  //   type: 'micro',
  //   data: [
  //     'We perform a comprehensive, flexible and risk-based approach data compliance audit that will bring enormous value in your organization',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data compliance audit',
  //   price: 24995,
  //   priceApi: 'price_1PeOluJrU3Or1CooyJQEb6ge',
  //   id: 54,
  //   type: 'sme',
  //   data: [
  //     'We perform a comprehensive, flexible and risk-based approach data compliance audit that will bring enormous value in your organization',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data processing agreement (drafting & negotiating)',
  //   price: 3500,
  //   priceApi: 'price_1PeOlwJrU3Or1CooPwoOqcjH',
  //   id: 55,
  //   type: 'startup',
  //   data: [
  //     'If you have more than 5 data processing agreements you can get in touch for your special discount or choose our vendor management module',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data processing agreement (drafting & negotiating)',
  //   price: 3500,
  //   priceApi: 'price_1PeOlwJrU3Or1CooPwoOqcjH',
  //   id: 56,
  //   type: 'micro',
  //   data: [
  //     'If you have more than 5 data processing agreements you can get in touch for your special discount or choose our vendor management module',
  //   ],
  //   option: 'product',
  // },
  // {
  //   title: 'Data processing agreement (drafting & negotiating)',
  //   price: 3500,
  //   priceApi: 'price_1PeOlwJrU3Or1CooPwoOqcjH',
  //   id: 57,
  //   type: 'sme',
  //   data: [
  //     'If you have more than 5 data processing agreements you can get in touch for your special discount or choose our vendor management module',
  //   ],
  //   option: 'product',
  // },
 
  
 
 
  
];
